#!/usr/bin/env bash
# Cross-compiles Stockfish for iOS (arm64) as a static library the app links.
#
# Runs on macOS with Xcode. Produces:
#   app/Vendor/lib/libstockfish.a      Stockfish with its NNUE net embedded,
#                                      entered through stockfish_main_c()
#   app/Vendor/stockfish.xcconfig      linker flag + version, included by lc0.xcconfig
#
# Environment knobs:
#   SF_REF   Stockfish tag/branch to build   (default: sf_19)
#   IOS_MIN  iOS deployment target           (default: 16.0)
set -euo pipefail

SF_REF="${SF_REF:-sf_19}"
IOS_MIN="${IOS_MIN:-16.0}"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$ROOT/build/stockfish"
VENDOR="$ROOT/app/Vendor"
mkdir -p "$VENDOR/lib"

if [ ! -d "$WORK/src/.git" ]; then
  rm -rf "$WORK/src"
  git clone -q --depth 1 -b "$SF_REF" https://github.com/official-stockfish/Stockfish.git "$WORK/src"
fi
SRC="$WORK/src/src"
SF_REV="$(git -C "$WORK/src" rev-parse --short HEAD)"

# The NNUE net gets embedded into the binary (incbin), so fetch it first.
make -C "$SRC" net

# iOS apps can't rely on POSIX shared memory; use Stockfish's no-shm fallback.
sed -i '' 's/|| defined(__APPLE__) ||/|| (defined(__APPLE__) \&\& !defined(SF_NO_SHM)) ||/' "$SRC/shm.h"
grep -q "SF_NO_SHM" "$SRC/shm.h"

# main() is renamed (only in main.cpp) and exposed to the app with C linkage.
cat > "$SRC/ios_entry.cpp" <<'EOF'
int stockfish_main(int argc, char* argv[]);
extern "C" int stockfish_main_c(int argc, char* argv[]) { return stockfish_main(argc, argv); }
EOF

SDK="$(xcrun --sdk iphoneos --show-sdk-path)"
CXX="$(xcrun --sdk iphoneos -f clang++)"
# Flags of Stockfish's apple-silicon build (neon, dot product, popcnt, prefetch).
FLAGS=(-arch arm64 -isysroot "$SDK" -miphoneos-version-min="$IOS_MIN"
       -std=c++17 -O3 -funroll-loops -fno-exceptions -DNDEBUG -DIS_64BIT
       -DUSE_POPCNT -DUSE_NEON=8 -DUSE_NEON_DOTPROD -DUSE_PREFETCH
       -march=armv8.2-a+dotprod -DSF_NO_SHM -Wno-deprecated-declarations)

SOURCES=$(sed -n '/^SRCS = /,/^$/p' "$SRC/Makefile" | sed 's/^SRCS = //; s/\\//g' | tr -s ' \n' '\n' | grep '\.cpp$')
OBJ="$WORK/obj"
rm -rf "$OBJ" && mkdir -p "$OBJ"
cd "$SRC"  # incbin resolves the net's path relative to here
for f in $SOURCES ios_entry.cpp; do
  extra=()
  [ "$f" = main.cpp ] && extra=(-Dmain=stockfish_main)
  echo "$CXX ${FLAGS[*]} ${extra[*]} -c $f -o $OBJ/$(echo "$f" | tr / _).o"
done > "$WORK/compile.txt"
# Compile in parallel.
tr '\n' '\0' < "$WORK/compile.txt" | xargs -0 -P "$(sysctl -n hw.ncpu)" -I{} sh -c '{}'

xcrun libtool -static -o "$VENDOR/lib/libstockfish.a" "$OBJ"/*.o
NET="$(grep -o 'nn-[0-9a-f]*\.nnue' "$SRC/evaluate.h" | head -1)"

cat > "$VENDOR/stockfish.xcconfig" <<EOF
// Generated by scripts/build_stockfish.sh -- do not edit.
SF_LDFLAGS = -lstockfish
LC0_STOCKFISH = Stockfish ${SF_REF#sf_} ($SF_REV, $NET)
EOF

echo "::notice::Built Stockfish $SF_REF ($SF_REV) with $NET, libstockfish.a $(stat -f%z "$VENDOR/lib/libstockfish.a") bytes"
